/**
 * vegawallet-service-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DelegateSubmissionBody } from './DelegateSubmissionBody';
import { DelegateSubmissionBodyDelegateSubmission } from './DelegateSubmissionBodyDelegateSubmission';
import { OrderAmendmentBody } from './OrderAmendmentBody';
import { OrderAmendmentBodyOrderAmendment } from './OrderAmendmentBodyOrderAmendment';
import { OrderCancellationBody } from './OrderCancellationBody';
import { OrderCancellationBodyOrderCancellation } from './OrderCancellationBodyOrderCancellation';
import { OrderSubmissionBody } from './OrderSubmissionBody';
import { OrderSubmissionBodyOrderSubmission } from './OrderSubmissionBodyOrderSubmission';
import { TransferSubmissionBody } from './TransferSubmissionBody';
import { TransferSubmissionBodyTransfer } from './TransferSubmissionBodyTransfer';
import { UndelegateSubmissionBody } from './UndelegateSubmissionBody';
import { UndelegateSubmissionBodyUndelegateSubmission } from './UndelegateSubmissionBodyUndelegateSubmission';
import { VoteSubmissionBody } from './VoteSubmissionBody';
import { VoteSubmissionBodyVoteSubmission } from './VoteSubmissionBodyVoteSubmission';
import { WithdrawSubmissionBody } from './WithdrawSubmissionBody';
import { WithdrawSubmissionBodyWithdrawSubmission } from './WithdrawSubmissionBodyWithdrawSubmission';
import { HttpFile } from '../http/http';

export class CommandSyncPostRequest {
    'pubKey': string;
    'propagate': boolean;
    'orderSubmission': OrderSubmissionBodyOrderSubmission;
    'orderCancellation': OrderCancellationBodyOrderCancellation;
    'withdrawSubmission': WithdrawSubmissionBodyWithdrawSubmission;
    'voteSubmission': VoteSubmissionBodyVoteSubmission;
    'delegateSubmission': DelegateSubmissionBodyDelegateSubmission;
    'undelegateSubmission': UndelegateSubmissionBodyUndelegateSubmission;
    'orderAmendment': OrderAmendmentBodyOrderAmendment;
    'transfer'?: TransferSubmissionBodyTransfer;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pubKey",
            "baseName": "pubKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "propagate",
            "baseName": "propagate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "orderSubmission",
            "baseName": "orderSubmission",
            "type": "OrderSubmissionBodyOrderSubmission",
            "format": ""
        },
        {
            "name": "orderCancellation",
            "baseName": "orderCancellation",
            "type": "OrderCancellationBodyOrderCancellation",
            "format": ""
        },
        {
            "name": "withdrawSubmission",
            "baseName": "withdrawSubmission",
            "type": "WithdrawSubmissionBodyWithdrawSubmission",
            "format": ""
        },
        {
            "name": "voteSubmission",
            "baseName": "voteSubmission",
            "type": "VoteSubmissionBodyVoteSubmission",
            "format": ""
        },
        {
            "name": "delegateSubmission",
            "baseName": "delegateSubmission",
            "type": "DelegateSubmissionBodyDelegateSubmission",
            "format": ""
        },
        {
            "name": "undelegateSubmission",
            "baseName": "undelegateSubmission",
            "type": "UndelegateSubmissionBodyUndelegateSubmission",
            "format": ""
        },
        {
            "name": "orderAmendment",
            "baseName": "orderAmendment",
            "type": "OrderAmendmentBodyOrderAmendment",
            "format": ""
        },
        {
            "name": "transfer",
            "baseName": "transfer",
            "type": "TransferSubmissionBodyTransfer",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommandSyncPostRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

