/**
 * vegawallet-service-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommandSyncOrderSubmission } from './CommandSyncOrderSubmission';
import { HttpFile } from '../http/http';

export class InlineObject1 {
    'pubKey'?: string;
    'orderSubmission'?: CommandSyncOrderSubmission;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pubKey",
            "baseName": "pubKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderSubmission",
            "baseName": "orderSubmission",
            "type": "CommandSyncOrderSubmission",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineObject1.attributeTypeMap;
    }

    public constructor() {
    }
}

