/**
 * vegawallet-service-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkConfig } from './NetworkConfig';
import { HttpFile } from '../http/http';

export class NetworkGet200Response {
    'network': NetworkConfig;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "network",
            "baseName": "network",
            "type": "NetworkConfig",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NetworkGet200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

