/**
 * vegawallet-service-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrderSubmissionBodyOrderSubmission {
    'marketId': string;
    'reference'?: string;
    'type': string;
    'side': string;
    'timeInForce': string;
    'size': string;
    'price'?: any;
    'expiresAt'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeInForce",
            "baseName": "timeInForce",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "any",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderSubmissionBodyOrderSubmission.attributeTypeMap;
    }

    public constructor() {
    }
}

