/**
 * vegawallet-service-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionResponseTxFrom } from './TransactionResponseTxFrom';
import { TransactionResponseTxSignature } from './TransactionResponseTxSignature';
import { HttpFile } from '../http/http';

export class TransactionResponseTx {
    '_from'?: TransactionResponseTxFrom;
    'inputData'?: string;
    'signature'?: TransactionResponseTxSignature;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_from",
            "baseName": "From",
            "type": "TransactionResponseTxFrom",
            "format": ""
        },
        {
            "name": "inputData",
            "baseName": "input_data",
            "type": "string",
            "format": ""
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "TransactionResponseTxSignature",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionResponseTx.attributeTypeMap;
    }

    public constructor() {
    }
}

