/**
 * vegawallet-service-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransferSubmissionBodyTransferOneOff } from './TransferSubmissionBodyTransferOneOff';
import { HttpFile } from '../http/http';

export class TransferSubmissionBodyTransfer {
    'fromAccountType': string;
    'toAccountType': string;
    'to': string;
    'amount': string;
    'asset': string;
    'oneOff'?: TransferSubmissionBodyTransferOneOff;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fromAccountType",
            "baseName": "fromAccountType",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAccountType",
            "baseName": "toAccountType",
            "type": "string",
            "format": ""
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "asset",
            "baseName": "asset",
            "type": "string",
            "format": ""
        },
        {
            "name": "oneOff",
            "baseName": "oneOff",
            "type": "TransferSubmissionBodyTransferOneOff",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransferSubmissionBodyTransfer.attributeTypeMap;
    }

    public constructor() {
    }
}

