/**
 * vegawallet-service-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UndelegateSubmissionBodyUndelegateSubmission {
    'nodeId': string;
    'amount': string;
    'method': UndelegateSubmissionBodyUndelegateSubmissionMethodEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nodeId",
            "baseName": "nodeId",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "UndelegateSubmissionBodyUndelegateSubmissionMethodEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UndelegateSubmissionBodyUndelegateSubmission.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UndelegateSubmissionBodyUndelegateSubmissionMethodEnum = "METHOD_NOW" | "METHOD_AT_END_OF_EPOCH" ;

