/**
 * vegawallet-service-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VegaKeyAlgorithm } from './VegaKeyAlgorithm';
import { VegaKeyMeta } from './VegaKeyMeta';
import { HttpFile } from '../http/http';

export class VegaKey {
    'index': number;
    'pub': string;
    'algorithm': VegaKeyAlgorithm;
    'tainted': boolean;
    'meta': Array<VegaKeyMeta>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "pub",
            "baseName": "pub",
            "type": "string",
            "format": ""
        },
        {
            "name": "algorithm",
            "baseName": "algorithm",
            "type": "VegaKeyAlgorithm",
            "format": ""
        },
        {
            "name": "tainted",
            "baseName": "tainted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "Array<VegaKeyMeta>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VegaKey.attributeTypeMap;
    }

    public constructor() {
    }
}

