/**
 * vegawallet-service-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VoteSubmissionBodyVoteSubmission } from './VoteSubmissionBodyVoteSubmission';
import { HttpFile } from '../http/http';

export class VoteSubmissionBody {
    'pubKey': string;
    'propagate': boolean;
    'voteSubmission': VoteSubmissionBodyVoteSubmission;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pubKey",
            "baseName": "pubKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "propagate",
            "baseName": "propagate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "voteSubmission",
            "baseName": "voteSubmission",
            "type": "VoteSubmissionBodyVoteSubmission",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VoteSubmissionBody.attributeTypeMap;
    }

    public constructor() {
    }
}

